# Generated by Django 5.0.1 on 2024-01-31 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='content',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.message'),
        ),
    ]
