# Generated by Django 5.0.1 on 2024-02-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customers',
        ),
    ]
