# Generated by Django 5.0.1 on 2024-02-03 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_order_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_response_customer',
            field=models.ManyToManyField(blank=True, related_name='last_response_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
