# Generated by Django 5.0.1 on 2024-02-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_last_response_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_response_customer',
        ),
    ]
