# Generated by Django 4.1.3 on 2023-04-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
