# Generated by Django 4.1.3 on 2023-03-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/shop'),
        ),
    ]
