# Generated by Django 4.1.3 on 2023-04-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.orderdata'),
        ),
    ]
