# Generated by Django 4.1.3 on 2023-04-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderdata_order_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
