# Generated by Django 4.1.3 on 2023-04-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderdata_city_orderdata_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
