# Generated by Django 4.1.3 on 2023-04-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_tags_item_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tag',
            new_name='tags',
        ),
    ]
