# Generated by Django 4.1.3 on 2023-03-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
